#pragma once

namespace ashbot {
    
enum class receive_type
{
    info,
    login,
    motd,
    list,
    join,
    kick,
    part,
    invite,
    quit,
    who,
    who_is,
    who_was,
    name,
    topic,
    ban_list,
    nick_change,
    topic_change,
    user_mode,
    user_mode_change,
    channel_mode,
    channel_mode_change,
    channel_message,
    channel_action,
    channel_notice,
    query_message,
    query_action,
    query_notice,
    ctcp_reply,
    ctcp_request,
    error,
    error_message,
    ping,
    cap_ack,
    unknown
};

enum class reply_code
{
    null = 000,
    welcome = 001,
    your_host = 002,
    created = 003,
    my_info = 004,
    bounce = 005,
    trace_link = 200,
    trace_connecting = 201,
    trace_handshake = 202,
    trace_unknown = 203,
    trace_operator = 204,
    trace_user = 205,
    trace_server = 206,
    trace_service = 207,
    trace_new_type = 208,
    trace_class = 209,
    trace_reconnect = 210,
    stats_link_info = 211,
    stats_commands = 212,
    end_of_stats = 219,
    user_mode_is = 221,
    service_list = 234,
    service_list_end = 235,
    stats_uptime = 242,
    stats_o_line = 243,
    luser_client = 251,
    luser_op = 252,
    luser_unknown = 253,
    luser_channels = 254,
    luser_me = 255,
    admin_me = 256,
    admin_location1 = 257,
    admin_location2 = 258,
    admin_email = 259,
    trace_log = 261,
    trace_end = 262,
    try_again = 263,
    away = 301,
    user_host = 302,
    is_on = 303,
    un_away = 305,
    now_away = 306,
    who_is_user = 311,
    who_is_server = 312,
    who_is_operator = 313,
    who_was_user = 314,
    end_of_who = 315,
    who_is_idle = 317,
    end_of_who_is = 318,
    who_is_channels = 319,
    list_start = 321,
    list = 322,
    list_end = 323,
    channel_mode_is = 324,
    unique_op_is = 325,
    no_topic = 331,
    topic = 332,
    inviting = 341,
    summoning = 342,
    invite_list = 346,
    end_of_invite_list = 347,
    exception_list = 348,
    end_of_exception_list = 349,
    version = 351,
    who_reply = 352,
    names_reply = 353,
    links = 364,
    end_of_links = 365,
    end_of_names = 366,
    ban_list = 367,
    end_of_ban_list = 368,
    end_of_who_was = 369,
    info = 371,
    motd = 372,
    end_of_info = 374,
    motd_start = 375,
    end_of_motd = 376,
    you_are_oper = 381,
    rehashing = 382,
    you_are_service = 383,
    time = 391,
    users_start = 392,
    users = 393,
    end_of_users = 394,
    no_users = 395,
    error_no_such_nickname = 401,
    error_no_such_server = 402,
    error_no_such_channel = 403,
    error_cannot_send_to_channel = 404,
    error_too_many_channels = 405,
    error_was_no_such_nickname = 406,
    error_too_many_targets = 407,
    error_no_such_service = 408,
    error_no_origin = 409,
    error_no_recipient = 411,
    error_no_text_to_send = 412,
    error_no_top_level = 413,
    error_wild_top_level = 414,
    error_bad_mask = 415,
    error_unknown_command = 421,
    error_no_motd = 422,
    error_no_admin_info = 423,
    error_file_error = 424,
    error_no_nickname_given = 431,
    error_erroneus_nickname = 432,
    error_nickname_in_use = 433,
    error_nickname_collision = 436,
    error_unavailable_resource = 437,
    error_user_not_in_channel = 441,
    error_not_on_channel = 442,
    error_user_on_channel = 443,
    error_no_login = 444,
    error_summon_disabled = 445,
    error_users_disabled = 446,
    error_not_registered = 451,
    error_need_more_params = 461,
    error_already_registered = 462,
    error_no_permission_for_host = 463,
    error_password_mismatch = 464,
    error_you_are_banned_creep = 465,
    error_you_will_be_banned = 466,
    error_key_set = 467,
    error_channel_is_full = 471,
    error_unknown_mode = 472,
    error_invite_only_channel = 473,
    error_banned_from_channel = 474,
    error_bad_channel_key = 475,
    error_bad_channel_mask = 476,
    error_no_channel_modes = 477,
    error_ban_list_full = 478,
    error_no_privileges = 481,
    error_channel_op_privileges_needed = 482,
    error_cannot_kill_server = 483,
    error_restricted = 484,
    error_unique_op_privileges_needed = 485,
    error_no_oper_host = 491,
    error_user_mode_unknown_flag = 501,
    error_users_do_not_match = 502
};

enum class send_type
{
    message,
    action,
    notice
};

}
